ALTER TABLE treatments ADD COLUMN IF NOT EXISTS images TEXT[] DEFAULT NULL;
ALTER TABLE treatments ADD COLUMN IF NOT EXISTS purchase_start_date DATE DEFAULT NULL;
ALTER TABLE treatments ADD COLUMN IF NOT EXISTS purchase_end_date DATE DEFAULT NULL;
ALTER TABLE treatments ADD COLUMN IF NOT EXISTS redeem_start_date DATE DEFAULT NULL;
ALTER TABLE treatments ADD COLUMN IF NOT EXISTS redeem_end_date DATE DEFAULT NULL;
ALTER TABLE treatments ADD COLUMN IF NOT EXISTS terms TEXT DEFAULT NULL;
